substitutions:
  _API_BASE_URL: "http://localhost:8080"

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:$BUILD_ID
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:$BUILD_ID

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - spotify
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:$BUILD_ID
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --min-instances
      - "0"
      - --max-instances
      - "2"
      - --cpu
      - "1"
      - --memory
      - 256Mi
      - --set-env-vars
      - API_BASE_URL=${_API_BASE_URL}
      - --labels
      - app=spotify,portfolio=junliu

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:$BUILD_ID
  - us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/spotify:latest

options:
  logging: CLOUD_LOGGING_ONLY
